### ISSUE TITLE
IllegalArgumentException in JSONDiff

### ISSUE THREAD

**Issue by roundhill** [Simperium/simperium-android#109]
Came across this error:

`FATAL EXCEPTION: simperium.processor.note
    Process: org.wordpress.android, PID: 7327
    java.lang.IllegalArgumentException: Delta length (83) smaller than source text length (87).
            at name.fraser.neil.plaintext.diff_match_patch.diff_fromDelta(diff_match_patch.java:1532)
            at com.simperium.util.JSONDiff.apply(JSONDiff.java:436)
            at com.simperium.util.JSONDiff.apply(JSONDiff.java:427)
            at com.simperium.util.JSONDiff.apply(JSONDiff.java:421)
            at com.simperium.client.Bucket.applyRemoteChange(Bucket.java:781)
            at com.simperium.client.Channel$ChangeProcessor.processRemoteChanges(Channel.java:1342)
            at com.simperium.client.Channel$ChangeProcessor.run(Channel.java:1252)
            at java.lang.Thread.run(Thread.java:841)`

Should we be catching an IllegalArgumentException here? https://github.com/Simperium/simperium-android/blob/develop/Simperium/src/main/java/com/simperium/client/Bucket.java#L775

**Comment by chengfred** [comment]
Do you have more details on the exception (the diff it was trying to apply and the data it was trying to apply it to)?

The fallback behavior for this should be: if we can't apply a change we should re-download that object

**Comment by beaucollins** [comment]
I think the Channel should catch the exception when calling applyRemoteChange since it knows how to request the objects data again.
