### ISSUE TITLE
SQLiteDatabaseLockedException

### ISSUE THREAD

**Issue by roundhill** [Simperium/simperium-android#111]
Crashed in WPAndroid:

```
05-17 07:40:30.272: E/AndroidRuntime(8149): FATAL EXCEPTION: simperium.processor.note
05-17 07:40:30.272: E/AndroidRuntime(8149): Process: org.wordpress.android, PID: 8149
05-17 07:40:30.272: E/AndroidRuntime(8149): android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
05-17 07:40:30.272: E/AndroidRuntime(8149):     at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
05-17 07:40:30.272: E/AndroidRuntime(8149):     at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
05-17 07:40:30.272: E/AndroidRuntime(8149):     at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
05-17 07:40:30.272: E/AndroidRuntime(8149):     at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
05-17 07:40:30.272: E/AndroidRuntime(8149):     at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:1497)
05-17 07:40:30.272: E/AndroidRuntime(8149):     at com.simperium.android.PersistentStore$DataStore$Reindexer.skip(PersistentStore.java:295)
05-17 07:40:30.272: E/AndroidRuntime(8149):     at com.simperium.android.PersistentStore$DataStore.save(PersistentStore.java:78)
05-17 07:40:30.272: E/AndroidRuntime(8149):     at com.simperium.client.Bucket.updateObject(Bucket.java:517)
05-17 07:40:30.272: E/AndroidRuntime(8149):     at com.simperium.client.Bucket.applyRemoteChange(Bucket.java:792)
05-17 07:40:30.272: E/AndroidRuntime(8149):     at com.simperium.client.Channel$ChangeProcessor.processRemoteChanges(Channel.java:1342)
05-17 07:40:30.272: E/AndroidRuntime(8149):     at com.simperium.client.Channel$ChangeProcessor.run(Channel.java:1252)
05-17 07:40:30.272: E/AndroidRuntime(8149):     at java.lang.Thread.run(Thread.java:841)
```

**Comment by beaucollins** [comment]
It sounds like this happens when a database is opened twice. But WP is using the default configuration of Simperium so it opens and maintains its own database connection.

https://code.google.com/p/ankidroid/issues/detail?id=1566

> The database should never be used by any other process, so the fact that it is locked might mean one of the two things:
> 1. we are opening the same database twice and that leads to a conflict
> 2. the app crashed and the system did not close the database

If [SimperiumUtils.configureSimperium](https://github.com/wordpress-mobile/WordPress-Android/blob/feature/simperium/src/org/wordpress/android/util/SimperiumUtils.java#L52) gets called more than once during an app launch this could happen, but this only ever gets called in `Application.onCreate` so I don't think that's the case.

**Comment by roundhill** [comment]
> but this only ever gets called in Application.onCreate so I don't think that's the case.

I did also make that call here after a user signs in and we have received their token: https://github.com/wordpress-mobile/WordPress-Android/blob/feature/simperium/src/org/wordpress/android/networking/OAuthAuthenticator.java#L99

Also, right before the fatal exception there were a flurry of these printed to the log:

```
05-17 07:40:29.952: E/Simperium.Bucket(8149): Unable to apply remote change RemoteChange 934160972 537774dba5cc2b680e045dd2 M 148-149
05-17 07:40:29.952: E/Simperium.Bucket(8149): com.simperium.client.RemoteChangeInvalidException: Local instance of 934160972 has source version of 149 and remote change has 148
05-17 07:40:29.952: E/Simperium.Bucket(8149):   at com.simperium.client.RemoteChange.apply(RemoteChange.java:108)
05-17 07:40:29.952: E/Simperium.Bucket(8149):   at com.simperium.client.Bucket.applyRemoteChange(Bucket.java:761)
05-17 07:40:29.952: E/Simperium.Bucket(8149):   at com.simperium.client.Channel$ChangeProcessor.processRemoteChanges(Channel.java:1342)
05-17 07:40:29.952: E/Simperium.Bucket(8149):   at com.simperium.client.Channel$ChangeProcessor.run(Channel.java:1252)
05-17 07:40:29.952: E/Simperium.Bucket(8149):   at java.lang.Thread.run(Thread.java:841)
05-17 07:40:29.952: E/Simperium.Channel(8149): Remote change could not be applied
05-17 07:40:29.952: E/Simperium.Channel(8149): com.simperium.client.RemoteChangeInvalidException: com.simperium.client.RemoteChangeInvalidException: Local instance of 934160972 has source version of 149 and remote change has 148
05-17 07:40:29.952: E/Simperium.Channel(8149):  at com.simperium.client.Bucket.applyRemoteChange(Bucket.java:797)
05-17 07:40:29.952: E/Simperium.Channel(8149):  at com.simperium.client.Channel$ChangeProcessor.processRemoteChanges(Channel.java:1342)
05-17 07:40:29.952: E/Simperium.Channel(8149):  at com.simperium.client.Channel$ChangeProcessor.run(Channel.java:1252)
05-17 07:40:29.952: E/Simperium.Channel(8149):  at java.lang.Thread.run(Thread.java:841)
05-17 07:40:29.952: E/Simperium.Channel(8149): Caused by: com.simperium.client.RemoteChangeInvalidException: Local instance of 934160972 has source version of 149 and remote change has 148
05-17 07:40:29.952: E/Simperium.Channel(8149):  at com.simperium.client.RemoteChange.apply(RemoteChange.java:108)
05-17 07:40:29.952: E/Simperium.Channel(8149):  at com.simperium.client.Bucket.applyRemoteChange(Bucket.java:761)
05-17 07:40:29.952: E/Simperium.Channel(8149):  ... 3 more
05-17 07:40:30.212: E/Watchdog(583): !@Sync 2847
05-17 07:40:30.242: E/Simperium.Bucket(8149): Unable to apply remote change RemoteChange 1161982075 537774dba5cc2b680e045dd6 M 146-147
05-17 07:40:30.242: E/Simperium.Bucket(8149): com.simperium.client.RemoteChangeInvalidException: Local instance of 1161982075 has source version of 147 and remote change has 146
05-17 07:40:30.242: E/Simperium.Bucket(8149):   at com.simperium.client.RemoteChange.apply(RemoteChange.java:108)
05-17 07:40:30.242: E/Simperium.Bucket(8149):   at com.simperium.client.Bucket.applyRemoteChange(Bucket.java:761)
05-17 07:40:30.242: E/Simperium.Bucket(8149):   at com.simperium.client.Channel$ChangeProcessor.processRemoteChanges(Channel.java:1342)
05-17 07:40:30.242: E/Simperium.Bucket(8149):   at com.simperium.client.Channel$ChangeProcessor.run(Channel.java:1252)
05-17 07:40:30.242: E/Simperium.Bucket(8149):   at java.lang.Thread.run(Thread.java:841)
05-17 07:40:30.242: E/Simperium.Channel(8149): Remote change could not be applied
05-17 07:40:30.242: E/Simperium.Channel(8149): com.simperium.client.RemoteChangeInvalidException: com.simperium.client.RemoteChangeInvalidException: Local instance of 1161982075 has source version of 147 and remote change has 146
05-17 07:40:30.242: E/Simperium.Channel(8149):  at com.simperium.client.Bucket.applyRemoteChange(Bucket.java:797)
05-17 07:40:30.242: E/Simperium.Channel(8149):  at com.simperium.client.Channel$ChangeProcessor.processRemoteChanges(Channel.java:1342)
05-17 07:40:30.242: E/Simperium.Channel(8149):  at com.simperium.client.Channel$ChangeProcessor.run(Channel.java:1252)
05-17 07:40:30.242: E/Simperium.Channel(8149):  at java.lang.Thread.run(Thread.java:841)
05-17 07:40:30.242: E/Simperium.Channel(8149): Caused by: com.simperium.client.RemoteChangeInvalidException: Local instance of 1161982075 has source version of 147 and remote change has 146
05-17 07:40:30.242: E/Simperium.Channel(8149):  at com.simperium.client.RemoteChange.apply(RemoteChange.java:108)
05-17 07:40:30.242: E/Simperium.Channel(8149):  at com.simperium.client.Bucket.applyRemoteChange(Bucket.java:761)
05-17 07:40:30.242: E/Simperium.Channel(8149):  ... 3 more
```

**Comment by beaucollins** [comment]
This could be a case of two Simperium instances fighting eachother. I think `SimperiumUtil.configureSimperium` should check for an existing static instance before creating a client again.

**Comment by roundhill** [comment]
OK, thanks. I will fix that WPAndroid side and close if it fixes the issue.

**Comment by beaucollins** [comment]
The log you posted fits with that theory since you would have two different clients processing changes but applying them to the same database, so the client that goes second will always fail to apply the remote change and get this error:

```
Local instance of 934160972 has source version of 149 and remote change has 148
```

**Comment by roundhill** [comment]
Aha! Yes I had signed out of one account and into another, which would have caused the dupe simperium to be created.

**Comment by roundhill** [comment]
@beaucollins is it safe to leave the existing static bucket instances as well, or should those be replaced if a different user signs in?

**Comment by beaucollins** [comment]
Yes, that's safe, you'll want to reset the buckets and close the socket connection though so the new user token will be used.

**Comment by roundhill** [comment]
Fixed over on WPAndroid side.
