### ISSUE TITLE
Full Text Search invalid SQL on API 15

### ISSUE THREAD

**Issue by beaucollins** [Simperium/simperium-android#150]
Failing test: [`PersistentStoreTest.testFullTextSnippet`](https://github.com/Simperium/simperium-android/blob/4454b018424e21c84ef20aeb5a24f3fe23007685/Simperium/src/androidTestSupport/java/com/simperium/PersistentStoreTest.java#L384)

Stacktrace

```
android.database.sqlite.SQLiteException: SQL logic error or missing database
at android.database.sqlite.SQLiteQuery.nativeFillWindow(Native Method)
at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:86)
at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:164)
at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:156)
at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:161)
at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:201)
at android.database.CursorWrapper.moveToFirst(CursorWrapper.java:65)
at android.database.CursorWrapper.moveToFirst(CursorWrapper.java:65)
at com.simperium.android.PersistentStoreTest.testFullTextSnippet(PersistentStoreTest.java:384)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:545)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1551)
```

**Comment by beaucollins** [comment]
It looks like the error appears between 0.4.7 and 0.4.8

**Comment by beaucollins** [comment]
Looks like `DISTINCT` [is to blame](https://github.com/Simperium/simperium-android/compare/0.4.7...0.4.8#diff-98de29c75c4e7a33e7850ab9fe9290b2R453)
