### ISSUE TITLE
Crash report from wpandroid 3.1.2 (using simperium 0.4.12): IllegalStateException: Timer was canceled

### ISSUE THREAD

**Issue by maxme** [Simperium/simperium-android#157]
```
java.lang.IllegalStateException: Timer was canceled
       at java.util.Timer.scheduleImpl(Timer.java:561)
       at java.util.Timer.schedule(Timer.java:459)
       at com.simperium.android.WebSocketManager.scheduleReconnect(WebSocketManager.java:317)
       at com.simperium.android.WebSocketManager.onDisconnect(WebSocketManager.java:425)
       at com.simperium.android.WebSocketManager$2.onDisconnect(WebSocketManager.java:216)
       at com.simperium.android.AsyncWebSocketProvider$1$4.onCompleted(AsyncWebSocketProvider.java:102)
       at com.koushikdutta.async.AsyncNetworkSocket.reportClose(AsyncNetworkSocket.java:201)
       at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:189)
       at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:766)
       at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:608)
       at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:37)
       at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:557)
```

**Comment by maxme** [comment]
This is the #1 crash on wpandroid 3.4.
