### ISSUE TITLE
Crash report 0.6.2: ConcurrentModificationException in JSONDiff.deepCopy

### ISSUE THREAD

**Issue by maxme** [Simperium/simperium-android#171]
We're seeing ~5 crashes / day on wpandroid 3.7 (using Simperium 0.6.2):

```
java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:806)
       at java.util.HashMap$EntryIterator.next(HashMap.java:843)
       at java.util.HashMap$EntryIterator.next(HashMap.java:841)
       at org.json.JSONObject.writeTo(JSONObject.java:671)
       at org.json.JSONStringer.value(JSONStringer.java:237)
       at org.json.JSONArray.writeTo(JSONArray.java:602)
       at org.json.JSONStringer.value(JSONStringer.java:233)
       at org.json.JSONObject.writeTo(JSONObject.java:672)
       at org.json.JSONObject.toString(JSONObject.java:641)
       at com.simperium.util.JSONDiff.deepCopy(JSONDiff.java:590)
       at org.wordpress.android.models.Note.getDiffableValue(Note.java:79)
       at com.simperium.android.PersistentStore$DataStore.save(PersistentStore.java:86)
       at com.simperium.client.Bucket$1.run(Bucket.java:195)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by roundhill** [comment]
Ref #176
