### ISSUE TITLE
NPE in RemoteChange

### ISSUE THREAD

**Issue by roundhill** [Simperium/simperium-android#18]
```
java.lang.NullPointerException
    at com.simperium.client.RemoteChange.isRemoveOperation(RemoteChange.java:128)
    at com.simperium.client.Bucket.applyRemoteChange(Bucket.java:663)
    at com.simperium.client.Channel$5.onRemote(Channel.java:167)
    at com.simperium.client.Channel$ChangeProcessor.processRemoteChanges(Channel.java:949)
    at com.simperium.client.Channel$ChangeProcessor.run(Channel.java:886)
    at java.lang.Thread.run(Thread.java:856)
```

**Comment by beaucollins** [comment]
Any other context to what was going on when this happened? Without seeing the raw socket data that triggered this it might be hard to diagnose but I can at least put in a null check.

**Comment by roundhill** [comment]
I've gotten this to happen a few times, here's some repro steps:
- Put your phone on an EDGE connection
- Share a large note from Simplenote to Simplenote ;)

Doesn't crash every time though :/

**Comment by beaucollins** [comment]
Can you get the logcat of Simperium.Websocket around the crash?

**Comment by roundhill** [comment]
```
08-29 13:30:38.543    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:62
08-29 13:30:58.553   8991-10042/? D/Simperium.Websocket: Timer-45 => h:63
08-29 13:30:59.213    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:64
08-29 13:31:19.213   8991-10078/? D/Simperium.Websocket: Timer-46 => h:65
08-29 13:31:20.814    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:66
08-29 13:31:40.814   8991-10201/? D/Simperium.Websocket: Timer-47 => h:67
08-29 13:31:42.285    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:68
08-29 13:32:02.285   8991-10245/? D/Simperium.Websocket: Timer-48 => h:69
08-29 13:32:02.995    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:70
08-29 13:32:22.995   8991-10306/? D/Simperium.Websocket: Timer-49 => h:71
08-29 13:32:23.656    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:72
08-29 13:32:43.655   8991-10393/? D/Simperium.Websocket: Timer-50 => h:73
08-29 13:32:44.776    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:74
08-29 13:33:04.776   8991-10425/? D/Simperium.Websocket: Timer-51 => h:75
08-29 13:33:05.456    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:76
08-29 13:33:25.456   8991-10430/? D/Simperium.Websocket: Timer-52 => h:77
08-29 13:33:26.177    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:78
08-29 13:33:46.176   8991-10453/? D/Simperium.Websocket: Timer-53 => h:79
08-29 13:33:47.517    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:80
08-29 13:34:07.517   8991-10458/? D/Simperium.Websocket: Timer-54 => h:81
08-29 13:34:08.208    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:82
08-29 13:34:28.217   8991-10476/? D/Simperium.Websocket: Timer-55 => h:83
08-29 13:34:28.948    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:84
08-29 13:34:48.947   8991-10478/? D/Simperium.Websocket: Timer-56 => h:85
08-29 13:34:49.648    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:86
08-29 13:35:09.658   8991-10482/? D/Simperium.Websocket: Timer-57 => h:87
08-29 13:35:10.428    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:88
08-29 13:35:30.438   8991-10484/? D/Simperium.Websocket: Timer-58 => h:89
08-29 13:35:31.128    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:90
08-29 13:35:51.138   8991-10503/? D/Simperium.Websocket: Timer-59 => h:91
08-29 13:35:51.809    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:92
08-29 13:36:11.818   8991-10508/? D/Simperium.Websocket: Timer-60 => h:93
08-29 13:36:12.509    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:94
08-29 13:36:32.508   8991-10510/? D/Simperium.Websocket: Timer-61 => h:95
08-29 13:36:33.229    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:96
08-29 13:36:53.239   8991-10512/? D/Simperium.Websocket: Timer-62 => h:97
08-29 13:36:53.949    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:98
08-29 13:37:13.949   8991-10526/? D/Simperium.Websocket: Timer-63 => h:99
08-29 13:37:14.649    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:100
08-29 13:37:34.659   8991-10528/? D/Simperium.Websocket: Timer-64 => h:101
08-29 13:37:35.360    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:102
08-29 13:37:55.369   8991-10530/? D/Simperium.Websocket: Timer-65 => h:103
08-29 13:37:56.090    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:104
08-29 13:38:16.099   8991-10535/? D/Simperium.Websocket: Timer-66 => h:105
08-29 13:38:16.850    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:106
08-29 13:38:36.860   8991-10537/? D/Simperium.Websocket: Timer-67 => h:107
08-29 13:38:37.550    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:108
08-29 13:38:57.560   8991-10539/? D/Simperium.Websocket: Timer-68 => h:109
08-29 13:38:58.231    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:110
08-29 13:39:18.240   8991-10543/? D/Simperium.Websocket: Timer-69 => h:111
08-29 13:39:18.951    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:112
08-29 13:39:38.950   8991-10545/? D/Simperium.Websocket: Timer-70 => h:113
08-29 13:39:39.731    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:114
08-29 13:39:59.741   8991-10548/? D/Simperium.Websocket: Timer-71 => h:115
08-29 13:40:00.431    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:116
08-29 13:40:20.431   8991-10552/? D/Simperium.Websocket: Timer-72 => h:117
08-29 13:40:21.151    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:118
08-29 13:40:41.151   8991-10554/? D/Simperium.Websocket: Timer-73 => h:119
08-29 13:40:41.852    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:120
08-29 13:41:01.851   8991-10556/? D/Simperium.Websocket: Timer-74 => h:121
08-29 13:41:02.552    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:122
08-29 13:41:22.551   8991-10562/? D/Simperium.Websocket: Timer-75 => h:123
08-29 13:41:23.292    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:124
08-29 13:41:43.302   8991-10564/? D/Simperium.Websocket: Timer-76 => h:125
08-29 13:41:43.952    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:126
08-29 13:42:03.952   8991-10568/? D/Simperium.Websocket: Timer-77 => h:127
08-29 13:42:04.632    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:128
08-29 13:42:24.642   8991-10605/? D/Simperium.Websocket: Timer-78 => h:129
08-29 13:42:25.433    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:130
08-29 13:42:45.432   8991-10615/? D/Simperium.Websocket: Timer-79 => h:131
08-29 13:42:46.123    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:132
08-29 13:43:06.122   8991-10810/? D/Simperium.Websocket: Timer-80 => h:133
08-29 13:43:06.833    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:134
08-29 13:43:26.833   8991-10855/? D/Simperium.Websocket: Timer-81 => h:135
08-29 13:43:27.533    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:136
08-29 13:43:47.543   8991-10875/? D/Simperium.Websocket: Timer-82 => h:137
08-29 13:43:54.950    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:138
08-29 13:44:14.960   8991-10884/? D/Simperium.Websocket: Timer-83 => h:139
08-29 13:44:15.760    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:140
08-29 13:44:35.760   8991-10886/? D/Simperium.Websocket: Timer-84 => h:141
08-29 13:44:36.731    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:142
08-29 13:44:56.730   8991-10899/? D/Simperium.Websocket: Timer-85 => h:143
08-29 13:44:57.491    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:144
08-29 13:45:17.501   8991-10969/? D/Simperium.Websocket: Timer-86 => h:145
08-29 13:45:18.191    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:146
08-29 13:45:38.191   8991-10971/? D/Simperium.Websocket: Timer-87 => h:147
08-29 13:45:38.871    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:148
08-29 13:45:58.881   8991-10975/? D/Simperium.Websocket: Timer-88 => h:149
08-29 13:45:59.562    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:150
08-29 13:46:19.561   8991-10985/? D/Simperium.Websocket: Timer-89 => h:151
08-29 13:46:20.242    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:152
08-29 13:46:40.241   8991-10988/? D/Simperium.Websocket: Timer-90 => h:153
08-29 13:46:40.902    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:154
08-29 13:47:00.901   8991-11001/? D/Simperium.Websocket: Timer-91 => h:155
08-29 13:47:01.562    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:156
08-29 13:47:21.572   8991-11011/? D/Simperium.Websocket: Timer-92 => h:157
08-29 13:47:22.603    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:158
08-29 13:47:42.602   8991-11014/? D/Simperium.Websocket: Timer-93 => h:159
08-29 13:47:43.963    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:160
08-29 13:48:03.963   8991-11019/? D/Simperium.Websocket: Timer-94 => h:161
08-29 13:48:04.694    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:162
08-29 13:48:24.703   8991-11022/? D/Simperium.Websocket: Timer-95 => h:163
08-29 13:48:25.604    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:164
08-29 13:48:45.604   8991-11028/? D/Simperium.Websocket: Timer-96 => h:165
08-29 13:48:46.334    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:166
08-29 13:49:06.334   8991-11046/? D/Simperium.Websocket: Timer-97 => h:167
08-29 13:49:07.044    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:168
08-29 13:49:27.044   8991-11052/? D/Simperium.Websocket: Timer-98 => h:169
08-29 13:49:27.675    8991-9013/? D/Simperium.Websocket: Thread-5910 <= h:170
08-29 15:17:06.457  14174-14174/com.automattic.simplenote D/Simperium: Initializing Simperium android-duo-beta
08-29 15:17:06.457  14174-14174/com.automattic.simplenote D/Simperium: Connecting to wss://api.simperium.com/sock/1/chalk-bump-f49/websocket
08-29 15:17:06.577  14174-14174/com.automattic.simplenote D/Simperium.Store: Query: FROM `objects`  LEFT JOIN indexes AS i0 ON objects.bucket = i0.bucket AND objects.key = i0.key AND i0.name=? LEFT JOIN indexes AS i1 ON objects.bucket = i1.bucket AND objects.key = i1.key AND i1.name=? LEFT JOIN indexes AS i2 ON objects.bucket = i2.bucket AND objects.key = i2.key AND i2.name=? WHERE objects.bucket = ? ORDER BY i2.value ASC,  objects.key ASC | [name, note_count, index, tag]
08-29 15:17:06.587  14174-14205/com.automattic.simplenote D/Simperium.Store: Query: FROM `objects`  LEFT JOIN indexes AS i0 ON objects.bucket = i0.bucket AND objects.key = i0.key AND i0.name=? LEFT JOIN indexes AS i1 ON objects.bucket = i1.bucket AND objects.key = i1.key AND i1.name=? LEFT JOIN indexes AS i2 ON objects.bucket = i2.bucket AND objects.key = i2.key AND i2.name=? LEFT JOIN indexes AS i3 ON objects.bucket = i3.bucket AND objects.key = i3.key AND i3.name=? LEFT JOIN indexes AS i4 ON objects.bucket = i4.bucket AND objects.key = i4.key AND i4.name=? WHERE objects.bucket = ? AND (  i0.value IS NULL OR i0.value !=  1) ORDER BY i3.value DESC,  i4.value DESC | [deleted, title, contentPreview, pinned, modificationDate, note]
08-29 15:17:09.370  14174-14174/com.automattic.simplenote D/Simperium.Store: Query: FROM `objects`  LEFT JOIN indexes AS i0 ON objects.bucket = i0.bucket AND objects.key = i0.key AND i0.name=? LEFT JOIN indexes AS i1 ON objects.bucket = i1.bucket AND objects.key = i1.key AND i1.name=? LEFT JOIN indexes AS i2 ON objects.bucket = i2.bucket AND objects.key = i2.key AND i2.name=? WHERE objects.bucket = ? ORDER BY i2.value ASC,  objects.key ASC | [name, note_count, index, tag]
08-29 15:17:09.400  14174-14223/com.automattic.simplenote D/Simperium.Store: Query: FROM `objects`  LEFT JOIN indexes AS i0 ON objects.bucket = i0.bucket AND objects.key = i0.key AND i0.name=? LEFT JOIN indexes AS i1 ON objects.bucket = i1.bucket AND objects.key = i1.key AND i1.name=? LEFT JOIN indexes AS i2 ON objects.bucket = i2.bucket AND objects.key = i2.key AND i2.name=? LEFT JOIN indexes AS i3 ON objects.bucket = i3.bucket AND objects.key = i3.key AND i3.name=? LEFT JOIN indexes AS i4 ON objects.bucket = i4.bucket AND objects.key = i4.key AND i4.name=? WHERE objects.bucket = ? AND (  i0.value IS NULL OR i0.value !=  1) ORDER BY i3.value DESC,  i4.value DESC | [deleted, title, contentPreview, pinned, modificationDate, note]
08-29 15:17:10.511  14174-14194/com.automattic.simplenote D/Simperium: Connected wss://api.simperium.com/sock/1/chalk-bump-f49/websocket
08-29 15:17:10.521  14174-14194/com.automattic.simplenote D/Simperium.Websocket: Thread-6027 => 1:init:{"clientid":"android-duo-beta-ece3ba","api":1,"app_id":"chalk-bump-f49","cmd":"cv:521f8e82ba5fdc52cc07db50","token":"23ddeef858dc45c788c2f0fd20d81591","name":"tag"}
08-29 15:17:10.521  14174-14194/com.automattic.simplenote D/Simperium.Websocket: Thread-6027 => 0:init:{"clientid":"android-duo-beta-ece3ba","api":1,"app_id":"chalk-bump-f49","cmd":"cv:521f9ec4ba5fdc52cc09123c","token":"23ddeef858dc45c788c2f0fd20d81591","name":"note"}
08-29 15:17:11.142  14174-14194/com.automattic.simplenote D/Simperium.Websocket: Thread-6027 <= 1:auth:danroundhill@gmail.com
08-29 15:17:11.162  14174-14194/com.automattic.simplenote D/Simperium.Websocket: Thread-6027 <= 1:o:{"schema": {"attributes": {"index": {"type": "integer"},
08-29 15:17:11.162  14174-14194/com.automattic.simplenote D/Simperium.Channel: Don't know how to run: o
08-29 15:17:11.262  14174-14194/com.automattic.simplenote D/Simperium.Websocket: Thread-6027 <= 1:c:[]
08-29 15:17:11.262  14174-14194/com.automattic.simplenote D/Simperium.Channel: Starting up the change processor with 0 remote and 0 local changes 0 pending
08-29 15:17:11.262  14174-14194/com.automattic.simplenote D/Simperium.Channel: Received 0 change(s)
08-29 15:17:11.262  14174-14236/com.automattic.simplenote D/Simperium.Channel: simperium.processor.tag - Starting change queue
08-29 15:17:11.392  14174-14238/com.automattic.simplenote D/Simperium.Cache: Miss f972c56a64e6436cbca3acff45e9739a
08-29 15:17:11.412  14174-14238/com.automattic.simplenote D/Simperium.Bucket: Fetched ghost for f972c56a64e6436cbca3acff45e9739a Ghost f972c56a64e6436cbca3acff45e9739a.13
08-29 15:17:11.422  14174-14238/com.automattic.simplenote D/Simperium.Syncable: Setting ghost f972c56a64e6436cbca3acff45e9739a Ghost f972c56a64e6436cbca3acff45e9739a.13
08-29 15:17:11.422  14174-14238/com.automattic.simplenote D/Simperium.Cache: Cache f972c56a64e6436cbca3acff45e9739a note - f972c56a64e6436cbca3acff45e9739a.13
08-29 15:17:11.452  14174-14243/com.automattic.simplenote D/Simperium.Store: Query: FROM `objects`  LEFT JOIN indexes AS i0 ON objects.bucket = i0.bucket AND objects.key = i0.key AND i0.name=? WHERE objects.bucket = ? ORDER BY i0.value ASC | [name, tag]
08-29 15:17:11.823  14174-14194/com.automattic.simplenote D/Simperium.Websocket: Thread-6027 <= 0:auth:danroundhill@gmail.com
08-29 15:17:11.843  14174-14194/com.automattic.simplenote D/Simperium.Websocket: Thread-6027 <= 0:o:{"schema": {"attributes": {"tags": {"item": {"type": "st
08-29 15:17:11.843  14174-14194/com.automattic.simplenote D/Simperium.Channel: Don't know how to run: o
08-29 15:17:11.843  14174-14194/com.automattic.simplenote D/Simperium.Websocket: Thread-6027 <= 0:c:[]
08-29 15:17:11.843  14174-14194/com.automattic.simplenote D/Simperium.Channel: Starting up the change processor with 0 remote and 0 local changes 0 pending
08-29 15:17:11.843  14174-14262/com.automattic.simplenote D/Simperium.Channel: simperium.processor.note - Starting change queue
08-29 15:17:11.843  14174-14194/com.automattic.simplenote D/Simperium.Channel: Received 0 change(s)
08-29 15:17:11.843  14174-14262/com.automattic.simplenote D/Simperium.Websocket: simperium.processor.note disconnect from socket
08-29 15:17:31.842  14174-14261/com.automattic.simplenote D/Simperium.Websocket: Timer-8 => h:1
08-29 15:17:32.783  14174-14194/com.automattic.simplenote D/Simperium.Websocket: Thread-6027 <= h:2
08-29 15:17:52.793  14174-14443/com.automattic.simplenote D/Simperium.Websocket: Timer-9 => h:3
08-29 15:17:53.493  14174-14194/com.automattic.simplenote D/Simperium.Websocket: Thread-6027 <= h:4
```

**Comment by roundhill** [comment]
That log might be from a different crash actually...

**Comment by beaucollins** [comment]
My suspicion is the client isn't getting a full message from the socket possibly due to a disconnection. If it's not due to a disconnect we should probably request changes manually otherwise we'll get them when we reconnect.

Either way we need to add some better parsing/error detection around RemoteChange.

**Comment by beaucollins** [comment]
I ran into this crash:

```
D/Simperium.Websocket( 3753): Thread-7405 <= 0:c:[{"error": 409, "ccids": ["59738aa2b5ce40ab9c6a36f37d8b0
E/AndroidRuntime( 3753): FATAL EXCEPTION: simperium.processor.note
E/AndroidRuntime( 3753): java.lang.NullPointerException
E/AndroidRuntime( 3753):    at com.simperium.client.RemoteChange.isRemoveOperation(RemoteChange.java:128)
E/AndroidRuntime( 3753):    at com.simperium.client.Bucket.applyRemoteChange(Bucket.java:651)
E/AndroidRuntime( 3753):    at com.simperium.client.Channel$5.onRemote(Channel.java:191)
E/AndroidRuntime( 3753):    at com.simperium.client.Channel$ChangeProcessor.processRemoteChanges(Channel.java:950)
E/AndroidRuntime( 3753):    at com.simperium.client.Channel$ChangeProcessor.run(Channel.java:888)
E/AndroidRuntime( 3753):    at java.lang.Thread.run(Thread.java:841)
```

Looks like there's some problems detecting change errors. In this case it sent the same change more than once (which would more likely happen when the network is spotty).
