### ISSUE TITLE
Dead Thread kills Sync

### ISSUE THREAD

**Issue by roundhill** [Simperium/simperium-android#182]
In WPAndroid I get the below exception while following a very specific set of steps:
1. Launch the app, load notifications tab.
2. Kill the app.
3. Send yourself a push notification and open it. You'll see that the note never synced.

```
java.lang.IllegalStateException: Handler (android.os.Handler) {9bc7899} sending message to a Handler on a dead thread
            at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
            at android.os.Handler.enqueueMessage(Handler.java:631)
            at android.os.Handler.sendMessageAtTime(Handler.java:600)
            at android.os.Handler.sendMessageDelayed(Handler.java:570)
            at android.os.Handler.post(Handler.java:326)
            at com.simperium.android.AsyncWebSocketProvider$1$1.send(AsyncWebSocketProvider.java:69)
            at com.simperium.android.WebSocketManager.send(WebSocketManager.java:228)
            at com.simperium.android.WebSocketManager.onMessage(WebSocketManager.java:355)
            at com.simperium.client.Channel.sendMessage(Channel.java:679)
            at com.simperium.client.Channel.start(Channel.java:631)
            at com.simperium.client.Channel.onConnect(Channel.java:650)
            at com.simperium.android.WebSocketManager.notifyChannelsConnected(WebSocketManager.java:271)
            at com.simperium.android.WebSocketManager.onConnect(WebSocketManager.java:394)
            at com.simperium.android.WebSocketManager$2.onConnect(WebSocketManager.java:207)
            at com.simperium.android.AsyncWebSocketProvider$1.onCompleted(AsyncWebSocketProvider.java:106)
            at com.koushikdutta.async.http.AsyncHttpClient$11.onConnectCompleted(AsyncHttpClient.java:699)
            at com.koushikdutta.async.http.AsyncHttpClient.reportConnectedCompleted(AsyncHttpClient.java:169)
            at com.koushikdutta.async.http.AsyncHttpClient.access$200(AsyncHttpClient.java:50)
            at com.koushikdutta.async.http.AsyncHttpClient$4.setDataEmitter(AsyncHttpClient.java:392)
            at com.koushikdutta.async.http.AsyncHttpResponseImpl.emitter(AsyncHttpResponseImpl.java:73)
            at com.koushikdutta.async.http.HttpTransportMiddleware$1.onStringAvailable(HttpTransportMiddleware.java:82)
            at com.koushikdutta.async.LineEmitter.onDataAvailable(LineEmitter.java:27)
            at com.koushikdutta.async.Util.emitAllData(Util.java:22)
            at com.koushikdutta.async.AsyncSSLSocketWrapper.onDataAvailable(AsyncSSLSocketWrapper.java:230)
            at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:217)
            at com.koushikdutta.async.Util.emitAllData(Util.java:22)
            at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
```

After some debugging with @beaucollins we discovered that using a HandlerThread in `AsyncWebSocketProvider` seems to solve the problem.

**Comment by beaucollins** [comment]
Essentially we have to make our own `Thread` since the thread that a simpler `Handler()` constructor call uses gets killed.
