### ISSUE TITLE
Recover from local instance version being more up to date than sync version. 

### ISSUE THREAD

**Issue by beaucollins** [Simperium/simperium-android#187]
Seen when attempting to sync on WordPress Android.

```
E/Simperium.Bucket: Unable to apply remote change RemoteChange 514965675 563ba2144806f92b41e4d6f7 M 8-9
E/Simperium.Bucket: com.simperium.client.RemoteChangeInvalidException: Local instance of 514965675 has source version of 9 and remote change has 8
E/Simperium.Bucket:     at com.simperium.client.RemoteChange.apply(RemoteChange.java:108)
E/Simperium.Bucket:     at com.simperium.client.Bucket.applyRemoteChange(Bucket.java:942)
E/Simperium.Bucket:     at com.simperium.client.Channel$ChangeProcessor.processRemoteChanges(Channel.java:1334)
E/Simperium.Bucket:     at com.simperium.client.Channel$ChangeProcessor.run(Channel.java:1240)
E/Simperium.Bucket:     at java.lang.Thread.run(Thread.java:818)
```

**Comment by chengfred** [comment]
If the local client legitimately has version 9, then a change with end version < current can be ignored, but it would be good if we had more info on the session to verify what circumstances were that led to this change being received (scenarios: 1. server re-sent change, less likely, but possible 2. client requested this (local `cv` was not advanced properly), maybe more likely 3. ?)

**Comment by fredrocious** [comment]
Test no more dupes?
