### ISSUE TITLE
SQLiteDatabaseLockedException in GhostStore

### ISSUE THREAD

**Issue by roundhill** [Simperium/simperium-android#190]
Reported in WP:

```
Fatal Exception: android.database.sqlite.SQLiteDatabaseLockedException: database is locked
       at android.database.sqlite.SQLiteStatement.native_executeSql(SQLiteStatement.java)
       at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:90)
       at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2019)
       at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1959)
       at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:683)
       at android.database.sqlite.SQLiteDatabase.beginTransactionNonExclusive(SQLiteDatabase.java:598)
       at android.database.sqlite.SQLiteStatement.acquireAndLock(SQLiteStatement.java:247)
       at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:112)
       at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1838)
       at com.simperium.android.GhostStore.saveGhost(GhostStore.java:117)
       at com.simperium.client.Bucket.applyRemoteChange(Bucket.java:946)
       at com.simperium.client.Channel$ChangeProcessor.processRemoteChanges(Channel.java:1334)
       at com.simperium.client.Channel$ChangeProcessor.run(Channel.java:1240)
       at java.lang.Thread.run(Thread.java:856)
```

**Comment by roundhill** [comment]
And another trace:

```

Fatal Exception: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
       at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
       at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
       at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
       at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:1497)
       at com.simperium.android.PersistentStore$DataStore.prepare(PersistentStore.java:75)
       at com.simperium.Simperium.bucket(Simperium.java:134)
       at com.simperium.Simperium.bucket(Simperium.java:116)
       at com.simperium.Simperium.bucket(Simperium.java:155)
       at org.wordpress.android.ui.notifications.utils.SimperiumUtils.configureSimperium(SimperiumUtils.java:50)
       at org.wordpress.android.GCMMessageService.handleDefaultPush(GCMMessageService.java:72)
       at org.wordpress.android.GCMMessageService.onMessageReceived(GCMMessageService.java:380)
       at com.google.android.gms.gcm.GcmListenerService.zzt(Unknown Source)
       at com.google.android.gms.gcm.GcmListenerService.zzk(Unknown Source)
       at com.google.android.gms.gcm.GcmListenerService.zza(Unknown Source)
       at com.google.android.gms.gcm.GcmListenerService$1.run(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by roundhill** [comment]
Closing here, the fix should be in WPAndroid

**Comment by beaucollins** [comment]
Nice. I feel like I've seen this during some unit testing in the emulator FWIW.
