### ISSUE TITLE
Invalid column name in SQL query

### ISSUE THREAD

**Issue by roundhill** [Simperium/simperium-android#30]
Google play report:

```
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:299)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
at java.util.concurrent.FutureTask.run(FutureTask.java:239)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:856)
Caused by: android.database.sqlite.SQLiteException: no such column: ١ (code 1): , while compiling: SELECT objects.rowid AS `_id`, objects.bucket || objects.key AS `key`, objects.key as `object_key`, objects.data as `object_data` , i١.value AS `title`, i٢.value AS `contentPreview`, i٣.value AS `pinned`, i٤.value AS `modificationDate`FROM `objects` LEFT JOIN indexes AS i٠ ON objects.bucket = i٠.bucket AND objects.key = i٠.key AND i٠.name=? LEFT JOIN indexes AS i١ ON objects.bucket = i١.bucket AND objects.key = i١.key AND i١.name=? LEFT JOIN indexes AS i٢ ON objects.bucket = i٢.bucket AND objects.key = i٢.key AND i٢.name=? LEFT JOIN indexes AS i٣ ON objects.bucket = i٣.bucket AND objects.key = i٣.key AND i٣.name=? LEFT JOIN indexes AS i٤ ON objects.bucket = i٤.bucket AND objects.key = i٤.key AND i٤.name=? WHERE objects.bucket = ? AND ( i٠.value IS NULL OR i٠.value != ١) ORDER BY i٣.value DESC, i٤.value DESC
at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:893)
at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:504)
at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1322)
at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1261)
at com.simperium.android.PersistentStore$QueryBuilder.query(PersistentStore.java:324)
at com.simperium.android.PersistentStore$DataStore.search(PersistentStore.java:202)
at com.simperium.client.Bucket.searchObjects(Bucket.java:313)
at com.simperium.client.Query.execute(Query.java:161)
at com.automattic.simplenote.NoteListFragment.queryNotes(NoteListFragment.java:353)
at com.automattic.simplenote.NoteListFragment$refreshListTask.doInBackground(NoteListFragment.java:545)
at com.automattic.simplenote.NoteListFragment$refreshListTask.doInBackground(NoteListFragment.java:539)
at android.os.AsyncTask$2.call(AsyncTask.java:287)
at java.util.concurrent.FutureTask.run(FutureTask.java:234)
... 3 more
```

**Comment by roundhill** [comment]
Looks like it might be caused by using Arabic characters, the crash comments from users were both in Arabic.

**Comment by beaucollins** [comment]
Strange, it's the table alias names. They should be `i0`, `i1`, `i2` but they're getting different characters.

**Comment by beaucollins** [comment]
Ran the unit tests against an emulator set to Arabic and reproduced the error. I need to use String.format with the locale set to Locale.US.
