### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by roundhill** [Simperium/simperium-android#32]
```
java.lang.IllegalArgumentException: Delta length (2889) smaller than source text length (2923).
at name.fraser.neil.plaintext.diff_match_patch.diff_fromDelta(diff_match_patch.java:1532)
at com.simperium.util.JSONDiff.apply(JSONDiff.java:203)
at com.simperium.util.JSONDiff.apply(JSONDiff.java:196)
at com.simperium.client.RemoteChange.apply(RemoteChange.java:88)
at com.simperium.client.RemoteChange.apply(RemoteChange.java:67)
at com.simperium.client.Bucket.applyRemoteChange(Bucket.java:654)
at com.simperium.client.Channel$5.onRemote(Channel.java:193)
at com.simperium.client.Channel$ChangeProcessor.processRemoteChanges(Channel.java:983)
at com.simperium.client.Channel$ChangeProcessor.run(Channel.java:924)
at java.lang.Thread.run(Thread.java:856)
```

**Comment by beaucollins** [comment]
Probably related to #39.

**Comment by beaucollins** [comment]
It appears this is because of a bad diff coming from the server probably from a client that incorrectly diffed strings with emoji in them due to differences in char sizes.

Our library handles emoji correctly and the service should no longer send patches that cause this issue with our jsondiff implementation.

We should protect ourselves from this in `RemoteChange.apply`.

**Comment by chengfred** [comment]
For max safety it should probably be handled like:

If a change from server causes a problem, client should catch it then request data for the "ev" of the problem change. Also pending in Simperium/simperium-js#10
