### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by roundhill** [Simperium/simperium-android#39]
Weird one:

```
java.lang.IllegalArgumentException: Delta length (1224) smaller than source text length (1228).
at a.a.a.a.a.g(Unknown Source)
at com.simperium.c.d.b(Unknown Source)
at com.simperium.c.d.b(Unknown Source)
at com.simperium.a.bo.a(Unknown Source)
at com.simperium.a.bo.a(Unknown Source)
at com.simperium.a.f.a(Unknown Source)
at com.simperium.a.ad.a(Unknown Source)
at com.simperium.a.aj.h(Unknown Source)
at com.simperium.a.aj.run(Unknown Source)
at java.lang.Thread.run(Thread.java:841)
```

**Comment by beaucollins** [comment]
Probably related to emoji.

**Comment by beaucollins** [comment]
This is a dup of #32.
