### ISSUE TITLE
Sync failing on KitKat

### ISSUE THREAD

**Issue by roundhill** [Simperium/simperium-android#46]
```
11-01 13:39:22.360    1028-1120/com.automattic.simplenote D/HybiParser﹕ Creating frame for: 0:init:{"clientid":"android-1.0-dab482","cmd":null,"token":"209b5a60064d4e53a5583a93e80315a5","name":"note","library":"android","api":1,"app_id":"chalk-bump-f49","version":0} op: 1 err: -1
11-01 13:39:22.430    1028-1120/com.automattic.simplenote D/HybiParser﹕ Got close op! 0 null
11-01 13:39:22.430    1028-1120/com.automattic.simplenote D/Simperium.Websocket﹕ Disconnect 0 null
11-01 13:39:22.430    1028-1120/com.automattic.simplenote D/Simperium﹕ Retrying in 3000
11-01 13:39:25.430    1028-1123/com.automattic.simplenote D/Simperium.Websocket﹕ Connecting to wss://api.simperium.com/sock/1/chalk-bump-f49/websocket
11-01 13:39:27.430    1028-1120/com.automattic.simplenote D/WebSocketClient﹕ WebSocket EOF!
    java.io.EOFException
            at java.io.DataInputStream.readByte(DataInputStream.java:77)
            at com.codebutler.android_websockets.HybiParser.start(HybiParser.java:112)
            at com.codebutler.android_websockets.WebSocketClient$1.run(WebSocketClient.java:139)
            at java.lang.Thread.run(Thread.java:841)
11-01 13:39:27.430    1028-1120/com.automattic.simplenote D/Simperium.Websocket﹕ Disconnect 0 EOF
11-01 13:39:27.430    1028-1120/com.automattic.simplenote D/Simperium﹕ Retrying in 3001
```

**Comment by beaucollins** [comment]
The problem is that the `cmd` property in the `init` message is `null`. ChannelTest shows the failure:

```
com.simperium.ChannelTest > testInitMessageWithNoChangeVersion[kitkat(AVD) - 4.4] FAILED 
    junit.framework.ComparisonFailure: expected:<...:"SESSION-ID","cmd":["i::::50"],"token":"fake-token...> but was:<...:"SESSION-ID","cmd":[null],"token":"fake-token...>
    at com.simperium.ChannelTest.testInitMessageWithNoChangeVersion(ChannelTest.java:229)
```
