### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by roundhill** [Simperium/simperium-android#76]
Just 3 reports of this:

```
java.util.ConcurrentModificationException
at java.util.ArrayList$ArrayListIterator.remove(ArrayList.java:586)
at com.simperium.client.Channel$ChangeProcessor.processRemoteChange(Unknown Source)
at com.simperium.client.Channel$ChangeProcessor.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:841)
```

**Comment by beaucollins** [comment]
Ooh. Our first threading issue.
