### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by roundhill** [Simperium/simperium-android#77]
1 report:

```
java.lang.StringIndexOutOfBoundsException: length=241; regionStart=238; regionLength=8
at java.lang.String.startEndAndLength(String.java:583)
at java.lang.String.substring(String.java:1464)
at com.automattic.simplenote.utils.MatchOffsetHighlighter.start(Unknown Source)
                                                          highlightMatches
                                                          highlightMatches
                                                          getByteOffset
                                                          access$200
at com.automattic.simplenote.utils.MatchOffsetHighlighter.start(Unknown Source)
                                                          highlightMatches
                                                          highlightMatches
                                                          getByteOffset
                                                          access$200
at com.automattic.simplenote.utils.MatchOffsetHighlighter.run(Unknown Source)
```

**Comment by beaucollins** [comment]
Hopefully we can find a deobfuscated stack trace of this.

**Comment by beaucollins** [comment]
The biggest issue here is how SQLite reports match ranges and how Java calculates string length. For now we should update the MatchOffsetHighlighter to protect against requesting out of bound ranges.
